### ISSUE TITLE
ultrono/laravel-sitemap

### ISSUE THREAD

**Issue by Sanjay1416** [ultrono/laravel-sitemap#10]
ultrono/laravel-sitemap not working on shared hsoting.Its showing white blank page.

**Comment by ultrono** [comment]
I have this exact package running on some awful shared hosting a client insists on using. It's generating a sitemap with ~`75,000` records without issue. What is the exact when you have error enabled?

**Comment by Sanjay1416** [comment]
Actually i found the issue its because while installing this package it create 2 vendor folder one in root and one in public folder in laravel .When i deleted public vendor folder its working now.

**Comment by abdulmoghni007** [comment]
or  save the same detail in both the folder or specify the prper path hope this will work

**Comment by ultrono** [comment]
Closing, as the reported issue is unrelated to the package itself.
