### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by jbeaven** [ultrono/laravel-sitemap#8]
Hey Rumen and Rob,

Any chance you'll be supporting Laravel 11? I had to uninstall the ultrono/laravel-sitemap dependency in order to upgrade from Laravel 10 to Laravel 11 :.( I see gulch forked the repo and tweaked, so I'll use that in the mean time :)

Thanks,

**Comment by ultrono** [comment]
Closing, resolved in #9 and #12 . Laravel 11 is now supported 🎊
